### PR TITLE
WIP: Para Cleanup - Do not delete bodies close to players

### PR DESCRIPTION
**Pull request by veteran29**
- title

Bodies near the players will be skipped, searches until it finds the bodies to clear or the array ended.

### CODE REVIEW

**Review by Spoffy — CHANGES_REQUESTED** [review]
I'm not sure this is the right way to solve this!

The reason behind adding overrunning bodies to `para_s_cleanup_items_delete_immediately` is performance. The "maximum 50 bodies" is a *hard* cap. 

If it becomes a soft cap, controlled by proximity to the player, the players could get swarmed, and surrounded by 500 bodies if they remain still. That's the situation that happened in MF, where players are often fighting in a relatively small area for long periods.

## Suggested fix
My suggested fix for this is actually to enable Arma 3's native garbage collection for bodies (which is enabled in Mike Force), and allow this to keep running as intended as an emergency fallback.

That means the oldest bodies will get cleaned up first, so players will see far fewer nearby bodies disappearing. 

## Alternative fix
The *alternative* would be to add dead bodies to this cleanup system on a time limit, by tweaking the "EntityKilled" handler in "fn_cleanup_subsystem_init", but I don't think we gain anything from having this system handle time-based deletion of bodies when Arma does those natively?

## Proposed changes either way
We could potentially increase the max dead bodies a little too, if we feel the need for more wiggle-room. Particularly given we'll have multiple teams on the mission, 100 feels more sane.

We could also make the emergency hard cap delete from the *front* of the bodies array, meaning we delete the oldest instead of the newest bodies.

**Comment by veteran29** [comment]
> My suggested fix for this is actually to enable Arma 3's native garbage collection for bodies

the Arma garbage collector is riddled with bugs and is unreliable, KK is working on fixing it but it most likely will be fixed in 2.18 (2.16 is next update) - https://feedback.bistudio.com/T171981

My issue with overrun handling is bodies vanishing right when you want to loot them which is more likely the more groups are playing on the server. This is pretty jarring and bad from gameplay flow.

**Comment by Spoffy** [comment]
> the Arma garbage collector is riddled with bugs and is unreliable, KK is working on fixing it but it most likely will be fixed in 2.18 (2.16 is next update) - https://feedback.bistudio.com/T171981

In that case, I'd propose we flip the body deletion to do the start of the array (oldest body first), and bump the limit up to 75 or 100.

That should probably solve 90% of the situations, without incurring a performance hit I'd think :D

**Comment by veteran29** [comment]
Can reopen when needed.

**Pull request closed without merging**
