### PR TITLE
Nightvision - Buff the effect for strong overcast

### PR DESCRIPTION
**Pull request by veteran29**
- title

The second stronger version of set aperture was never applied as its condition was inclusive in the first condition so it never was executed. (also present in current version of MF/Paradigm looking at the source)

### CODE REVIEW

**Comment by veteran29** [comment]
Might be too strong now, however the exampe is near the shore, it's darker in the jungle.

```sqf
setApertureNew [4, 6, 9, 0.9];
```
image

```sqf
private _minAperture = linearConversion [0, 4, _lightBrightness, 1, 3, true];
setApertureNew [_minAperture, 6, 9, 0.9];
```
image

**Review by Spoffy — CHANGES_REQUESTED** [review]
Is this definitely the fix? The comparison doesn't look right to me now.

What I see is this:
```
if (_lightBrightness < 4 && _lightBrightness < 120) exitWith { ... }

if (_lightBrightness <= 4 exitWith { ... }
```

**Comment by veteran29** [comment]
You're completly right! I hate conditions like this where the variable is not always on the same side, my brain completely ignored that.

Fixed this and added slight buff for the nightvision on higher overcast, which I think was the issue on our playtests.

**Review by Spoffy — APPROVED** [review]

**Comment by Spoffy** [comment]
> You're completly right! I hate conditions like this where the variable is not always on the same side, my brain completely ignored that.

Makes total sense! I stared at it for a good few minutes making sure I wasn't missing something :sweat_smile: 

The reason I do it that way is because it's similar to this: `4 < x < 120`, i.e the 'Between 4 and 120' expression. 
That said, happy for it to be changed :D

**Pull request merged**
